use std::collections::BTreeMap;

use crate::logger::ActivityEvent;

pub fn generate_ai_report(events: &[ActivityEvent], title_date: &str) -> String {
    if events.is_empty() {
        return format!("# System Activity Chronicle for {}\n\nNo activity logged for this period.", title_date);
    }

    let mut report = String::new();
    report.push_str(&format!("# System Activity Chronicle for {}\n\n", title_date));
    report.push_str("> Automated system log generated by `sys-chronicle` for AI context and behavior analysis.\n\n");

    // 1. Application Usage Statistics
    let mut app_totals: BTreeMap<String, u64> = BTreeMap::new();
    let mut timeline_blocks: Vec<String> = Vec::new();

    let mut current_app: Option<(String, String, String, u64)> = None; // (app_class, title, start_ts, duration)

    for event in events {
        if let ActivityEvent::WindowFocus {
            timestamp,
            app_class,
            title,
            duration_secs,
        } = event
        {
            let dur = duration_secs.unwrap_or(0);
            if dur > 0 && !app_class.is_empty() {
                *app_totals.entry(app_class.clone()).or_insert(0) += dur;
            }

            let short_time = extract_short_time(timestamp);

            if let Some((curr_class, curr_title, start_ts, curr_dur)) = current_app.as_mut() {
                if curr_class == app_class && curr_title == title {
                    *curr_dur += dur;
                } else {
                    if *curr_dur >= 5 {
                        timeline_blocks.push(format!(
                            "- `[{}]` **{}**: \"{}\" ({})",
                            start_ts, curr_class, curr_title, format_duration(*curr_dur)
                        ));
                    }
                    current_app = Some((app_class.clone(), title.clone(), short_time, dur));
                }
            } else {
                current_app = Some((app_class.clone(), title.clone(), short_time, dur));
            }
        }
    }

    if let Some((curr_class, curr_title, start_ts, curr_dur)) = current_app {
        if curr_dur >= 5 {
            timeline_blocks.push(format!(
                "- `[{}]` **{}**: \"{}\" ({})",
                start_ts, curr_class, curr_title, format_duration(curr_dur)
            ));
        }
    }

    report.push_str("## 1. Application Usage Summary\n");
    if app_totals.is_empty() {
        report.push_str("No application window switches recorded.\n\n");
    } else {
        let mut sorted_apps: Vec<_> = app_totals.into_iter().collect();
        sorted_apps.sort_by_key(|(_, dur)| std::cmp::Reverse(*dur));

        for (app, total_secs) in sorted_apps {
            report.push_str(&format!("- **{}**: {}\n", app, format_duration(total_secs)));
        }
        report.push_str("\n");
    }

    report.push_str("## 2. Chronological Active Application Timeline\n");
    if timeline_blocks.is_empty() {
        report.push_str("No active window focus blocks.\n\n");
    } else {
        for block in timeline_blocks.iter().take(100) {
            report.push_str(block);
            report.push_str("\n");
        }
        if timeline_blocks.len() > 100 {
            report.push_str(&format!("\n*... plus {} more activity blocks*\n", timeline_blocks.len() - 100));
        }
        report.push_str("\n");
    }

    // 2. Power & Battery Timeline
    report.push_str("## 3. Power & Charging Events\n");
    let mut power_events_count = 0;

    for event in events {
        if let ActivityEvent::PowerState {
            timestamp,
            status,
            capacity,
            ac_online,
        } = event
        {
            let time_str = extract_short_time(timestamp);
            let ac_str = if *ac_online { "AC Plugged" } else { "Battery Power" };
            report.push_str(&format!(
                "- `[{}]` Battery **{}%** | Status: **{}** ({})\n",
                time_str, capacity, status, ac_str
            ));
            power_events_count += 1;
        }
    }
    if power_events_count == 0 {
        report.push_str("No battery/power state changes logged.\n");
    }
    report.push_str("\n");

    // 3. System Load Metrics (CPU & Memory Spikes)
    report.push_str("## 4. CPU & RAM Resource Utilization\n");

    let mut cpu_samples = Vec::new();
    let mut ram_samples = Vec::new();
    let mut high_load_spikes = Vec::new();

    for event in events {
        if let ActivityEvent::SystemMetrics {
            timestamp,
            cpu_pct,
            ram_used_mb,
            ram_total_mb,
            ram_pct,
            top_apps,
        } = event
        {
            cpu_samples.push(*cpu_pct);
            ram_samples.push((*ram_used_mb, *ram_total_mb, *ram_pct));

            if *cpu_pct >= 70.0 || *ram_pct >= 85.0 {
                let time_str = extract_short_time(timestamp);
                high_load_spikes.push(format!(
                    "- `[{}]` CPU: **{:.1}%** | RAM: **{:.1}%** ({} / {} MB) | Top Apps: {}",
                    time_str,
                    cpu_pct,
                    ram_pct,
                    ram_used_mb,
                    ram_total_mb,
                    top_apps.join(", ")
                ));
            }
        }
    }

    if !cpu_samples.is_empty() {
        let avg_cpu: f32 = cpu_samples.iter().sum::<f32>() / cpu_samples.len() as f32;
        let max_cpu: f32 = cpu_samples.iter().cloned().fold(0.0, f32::max);

        let avg_ram: f32 = ram_samples.iter().map(|(_, _, p)| p).sum::<f32>() / ram_samples.len() as f32;
        let max_ram: f32 = ram_samples.iter().map(|(_, _, p)| *p).fold(0.0, f32::max);
        let max_ram_mb = ram_samples.iter().map(|(u, _, _)| *u).max().unwrap_or(0);
        let total_ram_mb = ram_samples.first().map(|(_, t, _)| *t).unwrap_or(0);

        report.push_str(&format!(
            "- **CPU Load**: Avg `{:.1}%` | Peak `{:.1}%`\n",
            avg_cpu, max_cpu
        ));
        report.push_str(&format!(
            "- **RAM Load**: Avg `{:.1}%` | Peak `{:.1}%` ({} / {} MB)\n\n",
            avg_ram, max_ram, max_ram_mb, total_ram_mb
        ));

        if !high_load_spikes.is_empty() {
            report.push_str("### Resource Spikes (>70% CPU or >85% RAM)\n");
            for spike in high_load_spikes.iter().take(20) {
                report.push_str(spike);
                report.push_str("\n");
            }
            report.push_str("\n");
        }
    } else {
        report.push_str("No system performance samples recorded.\n\n");
    }

    report
}

fn extract_short_time(ts: &str) -> String {
    // Input format: 2026-08-10T00:21:24.123+05:30 -> 00:21:24
    if let Some(time_part) = ts.split('T').nth(1) {
        let clean = time_part.split('+').next().unwrap_or(time_part);
        clean.split('.').next().unwrap_or(clean).to_string()
    } else {
        ts.to_string()
    }
}

fn format_duration(secs: u64) -> String {
    let hours = secs / 3600;
    let mins = (secs % 3600) / 60;
    let s = secs % 60;

    if hours > 0 {
        format!("{}h {}m", hours, mins)
    } else if mins > 0 {
        format!("{}m {}s", mins, s)
    } else {
        format!("{}s", s)
    }
}
