use std::collections::BTreeMap;

use crate::logger::ActivityEvent;

pub fn generate_ai_report(events: &[ActivityEvent], title_date: &str) -> String {
    if events.is_empty() {
        return format!("# System Activity Chronicle for {}\n\nNo activity logged for this period.", title_date);
    }

    let mut report = String::new();
    report.push_str(&format!("# System Activity Chronicle for {}\n\n", title_date));
    report.push_str("> Automated system log generated by `sys-chronicle` for AI context and behavior analysis.\n\n");

    // 1. Application Usage Statistics
    let mut app_totals: BTreeMap<String, u64> = BTreeMap::new();
    let mut app_titles: BTreeMap<String, BTreeMap<String, u64>> = BTreeMap::new();
    let mut brief_focus_totals: BTreeMap<String, (u64, u64)> = BTreeMap::new();
    let mut timeline_blocks: Vec<String> = Vec::new();

    let mut current_app: Option<(String, String, String, u64)> = None; // (app_class, title, start_ts, duration)

    for event in events {
        if let ActivityEvent::WindowFocus {
            timestamp,
            app_class,
            title,
            duration_secs,
        } = event
        {
            let dur = duration_secs.unwrap_or(0);
            if dur > 0 && !app_class.is_empty() {
                *app_totals.entry(app_class.clone()).or_insert(0) += dur;
                let clean_t = clean_window_title(title, app_class);
                if !clean_t.is_empty() {
                    *app_titles
                        .entry(app_class.clone())
                        .or_default()
                        .entry(clean_t)
                        .or_insert(0) += dur;
                }
                if dur < 5 {
                    let entry = brief_focus_totals.entry(app_class.clone()).or_insert((0, 0));
                    entry.0 += dur;
                    entry.1 += 1;
                }
            }

            let short_time = extract_short_time(timestamp);

            if let Some((curr_class, curr_title, start_ts, curr_dur)) = current_app.as_mut() {
                if curr_class == app_class && curr_title == title {
                    *curr_dur += dur;
                } else {
                    if *curr_dur >= 5 {
                        let display_t = clean_window_title(curr_title, curr_class);
                        if display_t.is_empty() {
                            timeline_blocks.push(format!(
                                "- `[{}]` **{}** ({})",
                                start_ts, curr_class, format_duration(*curr_dur)
                            ));
                        } else {
                            timeline_blocks.push(format!(
                                "- `[{}]` **{}**: \"{}\" ({})",
                                start_ts, curr_class, display_t, format_duration(*curr_dur)
                            ));
                        }
                    }
                    current_app = Some((app_class.clone(), title.clone(), short_time, dur));
                }
            } else {
                current_app = Some((app_class.clone(), title.clone(), short_time, dur));
            }
        }
    }

    if let Some((curr_class, curr_title, start_ts, curr_dur)) = current_app {
        if curr_dur >= 5 {
            let display_t = clean_window_title(&curr_title, &curr_class);
            if display_t.is_empty() {
                timeline_blocks.push(format!(
                    "- `[{}]` **{}** ({})",
                    start_ts, curr_class, format_duration(curr_dur)
                ));
            } else {
                timeline_blocks.push(format!(
                    "- `[{}]` **{}**: \"{}\" ({})",
                    start_ts, curr_class, display_t, format_duration(curr_dur)
                ));
            }
        }
    }

    report.push_str("## 1. Application Usage Summary\n");
    if app_totals.is_empty() {
        report.push_str("No application window switches recorded.\n\n");
    } else {
        let mut sorted_apps: Vec<_> = app_totals.into_iter().collect();
        sorted_apps.sort_by_key(|(_, dur)| std::cmp::Reverse(*dur));

        for (app, total_secs) in sorted_apps {
            report.push_str(&format!("- **{}**: {}\n", display_app_name(&app), format_duration(total_secs)));

            if let Some(titles) = app_titles.get(&app) {
                let mut sorted_titles: Vec<_> = titles.iter().collect();
                sorted_titles.sort_by_key(|(_, dur)| std::cmp::Reverse(**dur));

                for (t_name, t_dur) in sorted_titles.into_iter().take(5) {
                    if *t_dur >= 5 {
                        report.push_str(&format!("  - *\"{}\"*: {}\n", t_name, format_duration(*t_dur)));
                    }
                }
            }
        }
        report.push_str("\n");
    }

    if !brief_focus_totals.is_empty() {
        report.push_str("### Brief Focus Activity\n");
        report.push_str("> Short focus intervals are retained here instead of being omitted from the main timeline.\n\n");
        let mut brief_focus_totals: Vec<_> = brief_focus_totals.into_iter().collect();
        brief_focus_totals.sort_by_key(|(_, (duration, _))| std::cmp::Reverse(*duration));
        for (app, (duration, intervals)) in brief_focus_totals {
            report.push_str(&format!(
                "- **{}**: {} across {} interval{}\n",
                display_app_name(&app),
                format_duration(duration),
                intervals,
                if intervals == 1 { "" } else { "s" },
            ));
        }
        report.push_str("\n");
    }

    report.push_str("## 2. Chronological Active Application Timeline\n");
    if timeline_blocks.is_empty() {
        report.push_str("No active window focus blocks.\n\n");
    } else {
        for block in timeline_blocks.iter().take(100) {
            report.push_str(block);
            report.push_str("\n");
        }
        if timeline_blocks.len() > 100 {
            report.push_str(&format!("\n*... plus {} more activity blocks*\n", timeline_blocks.len() - 100));
        }
        report.push_str("\n");
    }

    // Process presence is intentionally kept separate from focus time. A process can be
    // doing useful work (for example, compiling in Android Studio) while another window
    // owns keyboard focus.
    let mut observed_apps: BTreeMap<String, AppObservation> = BTreeMap::new();
    for event in events {
        if let ActivityEvent::SystemMetrics { timestamp, top_apps, .. } = event {
            for top_app in top_apps {
                let name = top_app_name(top_app);
                if name.is_empty() {
                    continue;
                }
                let observation = observed_apps.entry(name).or_insert_with(|| AppObservation {
                    first_timestamp: timestamp.clone(),
                    last_timestamp: timestamp.clone(),
                    samples: 0,
                });
                observation.last_timestamp = timestamp.clone();
                observation.samples += 1;
            }
        }
    }

    report.push_str("## 3. Observed Running Applications\n");
    report.push_str("> Derived from periodic process samples. This indicates that an application was running among the largest processes; it is not focused-screen time.\n\n");
    let mut observed_apps: Vec<_> = observed_apps
        .into_iter()
        .filter(|(_, observation)| observation.samples >= 3)
        .collect();
    observed_apps.sort_by_key(|(_, observation)| std::cmp::Reverse(observation.samples));
    if observed_apps.is_empty() {
        report.push_str("No repeated process observations recorded.\n\n");
    } else {
        for (app, observation) in observed_apps.iter().take(12) {
            report.push_str(&format!(
                "- **{}**: observed in {} samples (`{}`–`{}`)\n",
                display_app_name(app),
                observation.samples,
                extract_short_time(&observation.first_timestamp),
                extract_short_time(&observation.last_timestamp),
            ));
        }
        report.push_str("\n");
    }

    // 4. Power & Battery Timeline
    report.push_str("## 4. Power & Charging Events\n");
    let mut power_events_count = 0;

    for event in events {
        if let ActivityEvent::PowerState {
            timestamp,
            status,
            capacity,
            ac_online,
        } = event
        {
            let time_str = extract_short_time(timestamp);
            let ac_str = if *ac_online { "AC Plugged" } else { "Battery Power" };
            report.push_str(&format!(
                "- `[{}]` Battery **{}%** | Status: **{}** ({})\n",
                time_str, capacity, status, ac_str
            ));
            power_events_count += 1;
        }
    }
    if power_events_count == 0 {
        report.push_str("No battery/power state changes logged.\n");
    }
    report.push_str("\n");

    // 5. System Load Metrics (CPU & Memory Spikes)
    report.push_str("## 5. CPU & RAM Resource Utilization\n");

    let mut cpu_samples = Vec::new();
    let mut ram_samples = Vec::new();
    let mut high_load_spikes = Vec::new();

    for event in events {
        if let ActivityEvent::SystemMetrics {
            timestamp,
            cpu_pct,
            ram_used_mb,
            ram_total_mb,
            ram_pct,
            top_apps,
        } = event
        {
            cpu_samples.push(*cpu_pct);
            ram_samples.push((*ram_used_mb, *ram_total_mb, *ram_pct));

            if *cpu_pct >= 70.0 || *ram_pct >= 85.0 {
                let time_str = extract_short_time(timestamp);
                high_load_spikes.push(format!(
                    "- `[{}]` CPU: **{:.1}%** | RAM: **{:.1}%** ({} / {} MB) | Top Apps: {}",
                    time_str,
                    cpu_pct,
                    ram_pct,
                    ram_used_mb,
                    ram_total_mb,
                    top_apps.join(", ")
                ));
            }
        }
    }

    if !cpu_samples.is_empty() {
        let avg_cpu: f32 = cpu_samples.iter().sum::<f32>() / cpu_samples.len() as f32;
        let max_cpu: f32 = cpu_samples.iter().cloned().fold(0.0, f32::max);

        let avg_ram: f32 = ram_samples.iter().map(|(_, _, p)| p).sum::<f32>() / ram_samples.len() as f32;
        let max_ram: f32 = ram_samples.iter().map(|(_, _, p)| *p).fold(0.0, f32::max);
        let max_ram_mb = ram_samples.iter().map(|(u, _, _)| *u).max().unwrap_or(0);
        let total_ram_mb = ram_samples.first().map(|(_, t, _)| *t).unwrap_or(0);

        report.push_str(&format!(
            "- **CPU Load**: Avg `{:.1}%` | Peak `{:.1}%`\n",
            avg_cpu, max_cpu
        ));
        report.push_str(&format!(
            "- **RAM Load**: Avg `{:.1}%` | Peak `{:.1}%` ({} / {} MB)\n\n",
            avg_ram, max_ram, max_ram_mb, total_ram_mb
        ));

        if !high_load_spikes.is_empty() {
            report.push_str("### Resource Spikes (>70% CPU or >85% RAM)\n");
            for spike in high_load_spikes.iter().take(20) {
                report.push_str(spike);
                report.push_str("\n");
            }
            report.push_str("\n");
        }
    } else {
        report.push_str("No system performance samples recorded.\n\n");
    }

    // 6. Media Playback & Player Events
    let mut media_events = Vec::new();
    for event in events {
        if let ActivityEvent::MediaPlayback {
            timestamp,
            player,
            event_type,
            title,
            position_secs,
            duration_secs,
            ..
        } = event
        {
            let time_str = extract_short_time(timestamp);
            let pos_str = format_duration(*position_secs);
            let dur_str = duration_secs.map(|d| format!(" / {}", format_duration(d))).unwrap_or_default();

            let action_desc = match event_type.as_str() {
                "start" => format!("Started watching *\"{}\"* at `{}`{}", title, pos_str, dur_str),
                "pause" => format!("Paused *\"{}\"* at `{}`{}", title, pos_str, dur_str),
                "resume" => format!("Resumed *\"{}\"* at `{}`{}", title, pos_str, dur_str),
                "seek_forward" => format!("Fast-forwarded *\"{}\"* to `{}`{}", title, pos_str, dur_str),
                "seek_backward" => format!("Rewound *\"{}\"* to `{}`{}", title, pos_str, dur_str),
                "stop" => format!("Stopped *\"{}\"* at `{}`{}", title, pos_str, dur_str),
                _ => format!("Event `{}` on *\"{}\"* at `{}`{}", event_type, title, pos_str, dur_str),
            };

            media_events.push(format!("- `[{}]` **{}**: {}", time_str, player, action_desc));
        }
    }

    if !media_events.is_empty() {
        report.push_str("## 6. Media Playback Chronicle\n");
        report.push_str("> Real-time media control events (play, pause, resume, seek, stop) captured from MPV IPC.\n\n");
        for event_str in media_events.iter().take(100) {
            report.push_str(event_str);
            report.push_str("\n");
        }
        report.push_str("\n");
    }

    report
}

fn extract_short_time(ts: &str) -> String {
    // Input format: 2026-08-10T00:21:24.123+05:30 -> 00:21:24
    if let Some(time_part) = ts.split('T').nth(1) {
        let clean = time_part.split('+').next().unwrap_or(time_part);
        clean.split('.').next().unwrap_or(clean).to_string()
    } else {
        ts.to_string()
    }
}

fn format_duration(secs: u64) -> String {
    let hours = secs / 3600;
    let mins = (secs % 3600) / 60;
    let s = secs % 60;

    if hours > 0 {
        format!("{}h {}m", hours, mins)
    } else if mins > 0 {
        format!("{}m {}s", mins, s)
    } else {
        format!("{}s", s)
    }
}

struct AppObservation {
    first_timestamp: String,
    last_timestamp: String,
    samples: u64,
}

fn top_app_name(top_app: &str) -> String {
    top_app
        .split_once(" (")
        .map(|(name, _)| name)
        .unwrap_or(top_app)
        .trim()
        .to_string()
}

fn display_app_name(app: &str) -> String {
    match app {
        "jetbrains-studio" | "studio" => format!("Android Studio ({})", app),
        _ => app.to_string(),
    }
}

fn clean_window_title(title: &str, _app_class: &str) -> String {
    let t = title.trim();
    if t.is_empty() {
        return String::new();
    }

    let suffixes = [
        " - mpv",
        " - Google Chrome",
        " - Visual Studio Code",
        " — Mozilla Firefox",
        " - Alacritty",
    ];

    let mut cleaned = t;
    for suffix in suffixes {
        if cleaned.ends_with(suffix) {
            cleaned = &cleaned[..cleaned.len() - suffix.len()];
        }
    }

    cleaned.trim().to_string()
}
